---
title: "Han_family"
output: html_document
date: '2022-07-24'
---

Upload of the peaks data
```{r}

cell_lines=c("HG00512", "HG00513", "HG00514")

experiment<<-"chiapet"

#peaks_extension
p_exp<<-1000

han_peaks_raw_ChIAPET=GRangesList("HG00512"=GRanges(), "HG00513"=GRanges(), "HG00514"=GRanges())

han_peaks_wout_sex_chr_ChIAPET=han_peaks_with_motif_ChIAPET=han_peaks_reduced_with_motif_ChIAPET=han_peaks_raw_ChIAPET


#Create GRangesLists that will conclude all the trios data

for (cell_line in cell_lines){
  
  han_peaks_raw_ChIAPET[[cell_line]]=read_peaks(get_peaks_path(experiment_1, cell_line))
  
  han_peaks_with_motif_ChIAPET[[cell_line]]=han_peaks_raw_ChIAPET[[cell_line]][unique(queryHits(findOverlaps(IRanges::reduce(han_peaks_raw_ChIAPET[[cell_line]]), IRanges::reduce(CTCF.hg38))))]
  
  han_peaks_reduced_with_motif_ChIAPET[[cell_line]]=IRanges::reduce(han_peaks_with_motif_ChIAPET[[cell_line]]+p_exp)

  han_peaks_wout_sex_chr_ChIAPET[[cell_line]]=subset(
    han_peaks_with_motif_ChIAPET[[cell_line]],
    !(han_peaks_with_motif_ChIAPET[[cell_line]]@seqnames %in% c('chrY', 'chrX', 'chrM')))
}


# Upload the peaks for two replicates
experiment<<-"chiapet"
cell_lines=c("LHH0073H", "LHH0094V", "LHH0074H", "LHG0086V","LHH0082H","LHH0126V")

han_rep2_peaks_raw_ChIAPET=GRangesList("LHH0073H"=GRanges(), "LHH0094V"=GRanges(),
                                  "LHH0074H"=GRanges(),"LHG0086V"=GRanges(),
                                  "LHH0082H"=GRanges(),"LHH0126V"=GRanges())

han_rep2_peaks_wout_sex_chr_ChIAPET=han_rep2_peaks_with_motif_ChIAPET=han_rep2_peaks_reduced_with_motif_ChIAPET=han_rep2_peaks_raw_ChIAPET

#Create GRangesLists that will conclude all the trios data

for (cell_line in cell_lines){
  
  han_rep2_peaks_raw_ChIAPET[[cell_line]]=read_peaks(get_peaks_path(experiment, cell_line))
  
  han_rep2_peaks_with_motif_ChIAPET[[cell_line]]=han_rep2_peaks_raw_ChIAPET[[cell_line]][unique(queryHits(findOverlaps(IRanges::reduce(han_rep2_peaks_raw_ChIAPET[[cell_line]]), IRanges::reduce(CTCF.hg38))))]
  
  han_rep2_peaks_reduced_with_motif_ChIAPET[[cell_line]]=IRanges::reduce(han_rep2_peaks_with_motif_ChIAPET[[cell_line]]+p_exp)
  
  han_rep2_peaks_wout_sex_chr_ChIAPET[[cell_line]]=subset(
    han_rep2_peaks_with_motif_ChIAPET[[cell_line]],
    !(han_rep2_peaks_with_motif_ChIAPET[[cell_line]]@seqnames %in% c('chrY', 'chrX', 'chrM')))
}

```
# Generation of BED files (peaks and bins)
```{r}

cell_lines=c("HG00512", "HG00513", "HG00514")

### ChIA-PET ###
# Converting peaks.gr into peaks.bed 
for (cell_line in cell_lines){
  write.table(unname(data.frame(seqnames(han_peaks_with_motif_ChIAPET[[cell_line]]), 
                                start(han_peaks_with_motif_ChIAPET[[cell_line]]), 
                                end(han_peaks_with_motif_ChIAPET[[cell_line]]))),
              paste0(abs_path, "/chiapet/", "/peaks_ChIAPET_", cell_line, ".bed"),
              sep="\t",row.names=FALSE, quote = FALSE)
}

#Generation of bins file
han_chiapet_bins=IRanges::reduce(unlist(han_peaks_with_motif_ChIAPET, recursive = TRUE, use.names = TRUE))
write.table(unname(data.frame(seqnames(han_chiapet_bins),
                              start(han_chiapet_bins),
                              end(han_chiapet_bins))),
            paste0(abs_path, "/chiapet/bins_han_ChIAPET.bed"),
            sep="\t",row.names=FALSE, quote = FALSE)

#Two replicates

cell_lines=c("LHH0073H", "LHH0094V", "LHH0074H", "LHG0086V","LHH0082H","LHH0126V")
# Converting peaks.gr into peaks.bed 
for (cell_line in cell_lines){
  write.table(unname(data.frame(
    seqnames(han_rep2_peaks_with_motif_ChIAPET[[cell_line]]),
    start(han_rep2_peaks_with_motif_ChIAPET[[cell_line]]),                             end(han_rep2_peaks_with_motif_ChIAPET[[cell_line]]))),
    paste0(abs_path, "/chiapet/", "/peaks_ChIAPET_", cell_line, ".bed"),
    sep="\t",row.names=FALSE, quote = FALSE)
}


```
# [Han ChIA-PET 2 rep] MANorm data processing
```{r}
experiment="chiapet"
cell_lines=c("LHH0073H", "LHH0094V", "LHH0074H", "LHG0086V","LHH0082H","LHH0126V")
trios=c("HG00512", "HG00513", "HG00514")

han_norm_inp_chiapet_2rep=data.frame(read.table(paste0(abs_path, "/", experiment, "/han_chiapet_2rep_profile_bins.xls"), header = T))


### Normalize between groups
han_norm_chiapet_2rep <- MAnorm2::normalize(han_norm_inp_chiapet_2rep, count = 4:5, occupancy = 10:11)
han_norm_chiapet_2rep <- MAnorm2::normalize(han_norm_chiapet_2rep, count = 6:7, occupancy = 12:13)
han_norm_chiapet_2rep <- MAnorm2::normalize(han_norm_chiapet_2rep, count = 8:9, occupancy = 14:15)

### Visualize the plots before/after normalization (Generating new plots and data (log2))
han_raw_chiapet_2rep = log(han_norm_inp_chiapet_2rep[4:9] + 0.5, base = 2)

png(paste0('plots/Han_ChIA-PET_MAnorm_2rep_normalization.png'), res = 300, width = 4200, height = 4200)

# Generating new plots and data (log2)
set_ylim<<-c(-2, 2)
par(mar=c(3,3,3,3))
layout(matrix(c(1,2,3,4,5,6,1,7,3,8,5,9),ncol=2),heights=c(1,3,1,3,1,3))
plot.new()
text(0.5,0.5,trios[[1]],cex=3,font=2)
generate_manorm_plot(cell_lines[1:2], han_norm_chiapet_2rep, han_raw_chiapet_2rep)
plot.new()
text(0.5,0.5,trios[[1]],cex=3,font=2)
generate_manorm_plot(cell_lines[3:4], han_norm_chiapet_2rep, han_raw_chiapet_2rep)
plot.new()
text(0.5,0.5,trios[[1]],cex=3,font=2)
generate_manorm_plot(cell_lines[5:6], han_norm_chiapet_2rep , han_raw_chiapet_2rep)
#After normalization
generate_manorm_plot(cell_lines[1:2], han_norm_chiapet_2rep)
generate_manorm_plot(cell_lines[3:4], han_norm_chiapet_2rep)
generate_manorm_plot(cell_lines[5:6], han_norm_chiapet_2rep)
dev.off()

### Construct a bioCond for each group of samples.
han_conds_chiapet_2rep_raw <- list(
  bioCond(han_norm_chiapet_2rep[4:5], han_norm_chiapet_2rep[10:11], name = trios[[1]]),
  bioCond(han_norm_chiapet_2rep[6:7], han_norm_chiapet_2rep[12:13], name = trios[[2]]),
  bioCond(han_norm_chiapet_2rep[8:9], han_norm_chiapet_2rep[14:15], name = trios[[3]]))
names(han_conds_chiapet_2rep_raw)=trios

### Perform between-group normalization.
autosome <- !(han_norm_inp_chiapet_2rep$chrom %in% c("chrX", "chrY"))
han_conds_chiapet_2rep <- normBioCond(han_conds_chiapet_2rep_raw, common.peak.regions = autosome)

# Drawing MA plots on bioCond objects to visualize the normalization results 

png(paste0('plots/Han_ChIA-PET_MAnorm_2rep_trios_normalization.png'), res = 300, width = 4200, height = 4200)
set_ylim<<-c(-2, 2)

# Generating new plots and data (log2)
par(mar=c(3,3,3,3))
layout(matrix(c(1,2,3,4,5,6,1,7,3,8,5,9),ncol=2),heights=c(1,3,1,3,1,3))
plot.new()
text(0.5,0.5,paste0(trios[1]," vs. ", trios[2]),cex=3,font=2)
generate_manorm_plot_trios(trios[1:2], han_conds_chiapet_2rep_raw, "before")
plot.new()
text(0.5,0.5,paste0(trios[1]," vs. ", trios[3]),cex=3,font=2)
generate_manorm_plot_trios(trios[c(1,3)], han_conds_chiapet_2rep_raw, "before")
plot.new()
text(0.5,0.5,paste0(trios[2]," vs. ", trios[3]),cex=3,font=2)
generate_manorm_plot_trios(trios[2:3], han_conds_chiapet_2rep_raw, "before")
#After normalization
generate_manorm_plot_trios(trios[1:2], han_conds_chiapet_2rep, "after")
generate_manorm_plot_trios(trios[c(1,3)], han_conds_chiapet_2rep, "after")
generate_manorm_plot_trios(trios[2:3], han_conds_chiapet_2rep, "after")
dev.off()

### Fit an MVC.
han_conds_chiapet_2rep <- fitMeanVarCurve(han_conds_chiapet_2rep, 
                                     method = "parametric", 
                                     occupy.only = TRUE,
                                     init.coef = c(0.1, 10))
### Plot only occupied genomic intervals,
# as only these intervals have been used to fit the MVC.
plotMeanVarCurve(han_conds_chiapet_2rep, subset = "occupied", ylim = c(-7, 0.5))

### Perform differential tests.
han_res_chiapet_rep2=list(
  aovBioCond(han_conds_chiapet_2rep),
  diffTest(han_conds_chiapet_2rep[[1]], han_conds_chiapet_2rep[[2]]),
  diffTest(han_conds_chiapet_2rep[[1]], han_conds_chiapet_2rep[[3]]),
  diffTest(han_conds_chiapet_2rep[[2]], han_conds_chiapet_2rep[[3]]))
names(han_res_chiapet_rep2)=c("all_trios", 
                              paste0(trios[1],"_",trios[2]),
                              paste0(trios[1],"_",trios[3]), 
                              paste0(trios[2],"_",trios[3]))

# Visualize the results

png(paste0('plots/Han_ChIA-PET_MAnorm_2rep_trios_diff_test_pval_0.05.png'), res = 300, width = 2200, height = 2200)
par(mar=c(2.3,2.3,2.3,2.3))
layout(matrix(c(1,2,3,4,1,5,3,4,1,6,3,4),ncol=3),heights=c(1,3,1,3,1,3))

plot.new()
text(0.5,0.5,"Within paris of trios ",cex=3,font=2)
MAplot(han_res_chiapet_rep2[[2]], pval = 0.05, ylim = c(-2, 2), main=paste0(trios[1]," vs. ", trios[2]), line=0.2)
abline(h = 0, lwd = 2, lty = 5, col = "green3")
plot.new()
text(0.5,0.5,"Within all trios ",cex=3,font=2)
plot(han_res_chiapet_rep2[[1]], pval = 0.05,line=0.2)
MAplot(han_res_chiapet_rep2[[3]], pval = 0.05,ylim = c(-2, 2), main=paste0(trios[1]," vs. ", trios[3]), line=0.2)
abline(h = 0, lwd = 2, lty = 5, col = "green3")
MAplot(han_res_chiapet_rep2[[4]], pval = 0.05,ylim = c(-2, 2), main=paste0(trios[2]," vs. ", trios[3]),line=0.2)
abline(h = 0, lwd = 2, lty = 5, col = "green3")
dev.off()

```

# [Han ChIA-PET 2 rep] Analysis of the results
```{r}
experiment="ChIA-PET"

# Create tables that will include all important information for the analysis
han_common_chiapet_manorm=list(
  create_table_common_peaks_with_info(han_norm_chiapet_2rep, han_res_chiapet_rep2, han_conds_chiapet_2rep, trios[1:2]),        
  create_table_common_peaks_with_info(han_norm_chiapet_2rep, han_res_chiapet_rep2, han_conds_chiapet_2rep, trios[c(1,3)]),          
  create_table_common_peaks_with_info(han_norm_chiapet_2rep, han_res_chiapet_rep2, han_conds_chiapet_2rep, trios[2:3]))

names(han_common_chiapet_manorm)=create_short_name_for_col(trios)
                                   
# Create additional tables with lower and higher values of mean values (select the squares)
mean_range=c(10,10)

han_common_chiapet_manorm=add_greater_and_lower_mean_ranges_tables(han_common_chiapet_manorm, mean_range, trios[1:2])
han_common_chiapet_manorm=add_greater_and_lower_mean_ranges_tables(han_common_chiapet_manorm, mean_range, trios[c(1,3)])
han_common_chiapet_manorm=add_greater_and_lower_mean_ranges_tables(han_common_chiapet_manorm, mean_range, trios[2:3])
            
# Create false pos tables                                    
par="isPval"
prefix="_mrgBins_Han"
han_pos_false_tables_chiapet=list(
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[1]],trios[1:2], experiment, paste0("all",prefix), par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[4]],trios[1:2], experiment, paste0("mean>=10",prefix), par),      
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[5]],trios[1:2], experiment, paste0("mean<10",prefix), par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[2]],trios[c(1,3)], experiment, paste0("all",prefix), par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[6]],trios[c(1,3)], experiment, paste0("mean>=10",prefix), par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[7]],trios[c(1,3)], experiment, paste0("mean<10",prefix), par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[3]],trios[2:3], experiment, paste0("all",prefix), par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[8]],trios[2:3], experiment, paste0("mean>=10",prefix), par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm[[9]],trios[2:3], experiment, paste0("mean<10",prefix), par))
names(han_pos_false_tables_chiapet)=names(han_common_chiapet_manorm)[c(1,4,5,2,6,7,3,8,9)]
rm(prefix)
               
# Create confusion tables               
han_confusion_tables_chiapet=vector(mode="list", length=NROW(han_pos_false_tables_chiapet))
names(han_confusion_tables_chiapet)=names(han_pos_false_tables_chiapet)
for (i in 1:NROW(han_confusion_tables_chiapet)){
  han_confusion_tables_chiapet[i]=list(
    caret::confusionMatrix(factor(han_common_chiapet_manorm[[names(han_confusion_tables_chiapet)[i]]]$common_pval, levels=c(TRUE, FALSE)), 
                        factor(han_common_chiapet_manorm[[names(han_confusion_tables_chiapet)[i]]]$predicted_rev, levels=c(TRUE, FALSE)),
                       dnn=c("pval>0.05", "SPP_detected")))
}

# 4 CASES
han_confusion_data_chiapet=list(
       # Both show common (TP)
  list(TP=han_pos_false_tables_chiapet[[1]][[1]][han_pos_false_tables_chiapet[[1]][[1]]$common_pval==TRUE,],
       # Spp pokazuje tak, a padj pokazuje róźną siłę (FP)
       FP=han_pos_false_tables_chiapet[[1]][[1]][han_pos_false_tables_chiapet[[1]][[1]]$common_pval==FALSE,], 
       # SPP pokazuje nie, a padj pokazuje, że siła jest taka sama (FN)
       FN=han_pos_false_tables_chiapet[[1]][["false_peaks"]][han_pos_false_tables_chiapet[[1]][["false_peaks"]]$common_pval==TRUE,],
       # SPP pokazuje nie i padj się zgadza  (TN)
       TN=han_pos_false_tables_chiapet[[1]][["false_peaks"]][han_pos_false_tables_chiapet[[1]][["false_peaks"]]$common_pval==FALSE,]),
  list(TP=han_pos_false_tables_chiapet[[4]][[1]][han_pos_false_tables_chiapet[[4]][[1]]$common_pval==TRUE,],
       
       # Spp pokazuje tak, a padj pokazuje róźną siłę (FP)
       FP=han_pos_false_tables_chiapet[[4]][[1]][han_pos_false_tables_chiapet[[4]][[1]]$common_pval==FALSE,],
       # SPP pokazuje nie, a padj pokazuje, że siła jest taka sama (FN)
       FN=han_pos_false_tables_chiapet[[4]][["false_peaks"]][han_pos_false_tables_chiapet[[4]][["false_peaks"]]$common_pval==TRUE,],
       # SPP pokazuje nie i padj się zgadza  (TN)
       TN=han_pos_false_tables_chiapet[[4]][["false_peaks"]][han_pos_false_tables_chiapet[[4]][["false_peaks"]]$common_pval==FALSE,]),
  
  list(TP=han_pos_false_tables_chiapet[[7]][[1]][han_pos_false_tables_chiapet[[7]][[1]]$common_pval==TRUE,],
       # Spp pokazuje tak, a padj pokazuje róźną siłę (FP)
       FP=han_pos_false_tables_chiapet[[7]][[1]][han_pos_false_tables_chiapet[[7]][[1]]$common_pval==FALSE,],
       # SPP pokazuje nie, a padj pokazuje, że siła jest taka sama (FN)
       FN=han_pos_false_tables_chiapet[[7]][["false_peaks"]][han_pos_false_tables_chiapet[[7]][["false_peaks"]]$common_pval==TRUE,],
       # SPP pokazuje nie i padj się zgadza  (TN)
       TN=han_pos_false_tables_chiapet[[7]][["false_peaks"]][han_pos_false_tables_chiapet[[7]][["false_peaks"]]$common_pval==FALSE,]))

names(han_confusion_data_chiapet)=names(han_common_chiapet_manorm)[1:3]

```

# [HAN ChIA-PET merged] MANorm data processing
```{r}
experiment="chiapet"
trios=c("HG00512", "HG00513", "HG00514")
han_norm_inp_chiapet=data.frame(read.table(paste0(abs_path, "/", experiment, "/han_chiapet_merged_profile_bins.xls"), header = T))

### Visualize the plots before/after normalization (Generating new plots and data (log2))
han_raw_chiapet = log(han_norm_inp_chiapet[4:6] + 0.5, base = 2)

### Normalize between cell lines
autosome <- !(han_norm_inp_chiapet$chrom %in% c("chrX", "chrY"))
han_norm_chiapet <- normalize(han_norm_inp_chiapet, c(4:6), c(7:9), common.peak.regions = autosome)

png(paste0('plots/Han_',experiment,'_MAnorm_merRep_normalization.png'), res = 300, width = 4200, height = 4200)

# Generating new plots and data (log2)
set_ylim<<-c(-2,2)
par(mar=c(3,3,3,3))
layout(matrix(c(1,2,3,4,5,6,1,7,3,8,5,9),ncol=2),heights=c(1,3,1,3,1,3))
plot.new()
text(0.5,0.5,paste0(trios[1],' vs. ', trios[2]),cex=3,font=2)
generate_manorm_plot(trios[1:2], han_norm_chiapet, han_raw_chiapet)
plot.new()
text(0.5,0.5,paste0(trios[1],' vs. ', trios[3]),cex=3,font=2)
generate_manorm_plot(trios[c(1,3)], han_norm_chiapet, han_raw_chiapet)
plot.new()
text(0.5,0.5,paste0(trios[2],' vs. ', trios[3]),cex=3,font=2)
generate_manorm_plot(trios[2:3], han_norm_chiapet , han_raw_chiapet)
#After normalization
generate_manorm_plot(trios[1:2], han_norm_chiapet)
generate_manorm_plot(trios[c(1,3)], han_norm_chiapet)
generate_manorm_plot(trios[2:3], han_norm_chiapet)
dev.off()

### Construct a bioCond for each group of samples.
han_conds_chiapet <- list(
  bioCond(han_norm_chiapet[4], han_norm_chiapet[7], name = trios[1]),
  bioCond(han_norm_chiapet[5], han_norm_chiapet[8], name = trios[2]),
  bioCond(han_norm_chiapet[6], han_norm_chiapet[9], name = trios[3]))
names(han_conds_chiapet)=trios

### Perform between-group normalization.
# autosome <- !(norm_inp_hichip$chrom %in% c("chrX", "chrY"))
# han_conds_chiapet$blind=bioCond()
# conds_hichip <- normBioCond(conds_hichip_2rep_raw, common.peak.regions = autosome)

### Create a "blind" biocond, to compare two groups and not two samples

han_conds_chiapet$blind_1 <- bioCond(han_norm_chiapet[c(4, 5)], han_norm_chiapet[c(7, 8)], occupy.num = 2)
han_conds_chiapet$blind_2 <- bioCond(han_norm_chiapet[c(4, 6)], han_norm_chiapet[c(7, 9)], occupy.num = 2)
han_conds_chiapet$blind_3 <- bioCond(han_norm_chiapet[c(5, 6)], han_norm_chiapet[c(8, 9)], occupy.num = 2)
han_conds_chiapet$blind_common <- bioCond(han_norm_chiapet[c(4, 5, 6)], han_norm_chiapet[c(7, 8, 9)], occupy.num = 3)

names(han_conds_chiapet)[4:7]=c(paste0("blind_", trios[1],"_",trios[2]), 
                           paste0("blind_", trios[1],"_",trios[3]),
                           paste0("blind_", trios[2],"_",trios[3]),
                           "blind_common")


han_conds_chiapet_meanCurve=list(fitMeanVarCurve(han_conds_chiapet[c(1, 2, 3, 7)], method = "parametric",
                         occupy.only = TRUE, init.coef = c(0.1, 10)),
                            fitMeanVarCurve(han_conds_chiapet[c(1, 2, 4)], method = "parametric",
                         occupy.only = TRUE, init.coef = c(0.1, 10)),
                            fitMeanVarCurve(han_conds_chiapet[c(1, 3, 5)], method = "parametric",
                         occupy.only = TRUE, init.coef = c(0.1, 10)),
                            fitMeanVarCurve(han_conds_chiapet[c(2, 3, 6)], method = "parametric",
                         occupy.only = TRUE, init.coef = c(0.1, 10)))
names(han_conds_chiapet_meanCurve)=c("all_trios", 
                                     paste0(trios[1],"_",trios[2]),
                                     paste0(trios[1],"_",trios[3]),
                                     paste0(trios[2],"_",trios[3]))

# Visualize mean-variance trend along with the fitted MVC. Plots are not being saved
plotMeanVarCurve(han_conds_chiapet_meanCurve[[2]][3], subset = "occupied", ylim = c(-7, 1))
plotMeanVarCurve(han_conds_chiapet_meanCurve[[3]][3], subset = "occupied", ylim = c(-7, 1))
plotMeanVarCurve(han_conds_chiapet_meanCurve[[4]][3], subset = "occupied", ylim = c(-7, 1))
plotMeanVarCurve(han_conds_chiapet_meanCurve$all_trios[4], subset = "occupied", ylim = c(-7, 1))

### # Perform differential tests
han_res_chiapet=list(
  aovBioCond(han_conds_chiapet_meanCurve[[1]]),
  diffTest(han_conds_chiapet_meanCurve[[2]][[1]], han_conds_chiapet_meanCurve[[2]][[2]]),
  diffTest(han_conds_chiapet_meanCurve[[3]][[1]], han_conds_chiapet_meanCurve[[3]][[2]]),
  diffTest(han_conds_chiapet_meanCurve[[4]][[1]], han_conds_chiapet_meanCurve[[4]][[2]]))
names(han_res_chiapet)=names(han_conds_chiapet_meanCurve)

# Visualize the results

png(paste0('plots/Han_',experiment,'_MAnorm_merRep_trios_diff_test.png'), res = 300, width = 2200, height = 2200)
par(mar=c(2.3,2.3,2.3,2.3))
layout(matrix(c(1,2,3,4,1,5,3,4,1,6,3,4),ncol=3),heights=c(1,3,1,3,1,3))

plot.new()
text(0.5,0.5,"Within paris of trios ",cex=3,font=2)
MAplot(han_res_chiapet[[2]], pval = 0.05, ylim = c(-2, 2), main=paste0(trios[1]," vs. ",trios[2]), line=0.2)
abline(h = 0, lwd = 2, lty = 5, col = "green3")
plot.new()
text(0.5,0.5,"Within all trios ",cex=3,font=2)
plot(han_res_chiapet[[1]], pval = 0.05,line=0.2)
MAplot(han_res_chiapet[[3]], pval = 0.05,ylim = c(-2, 2), main=paste0(trios[1]," vs. ",trios[3]), line=0.2)
abline(h = 0, lwd = 2, lty = 5, col = "green3")
MAplot(han_res_chiapet[[4]], pval = 0.05,ylim = c(-2, 2), main=paste0(trios[2]," vs. ",trios[3]),line=0.2)
abline(h = 0, lwd = 2, lty = 5, col = "green3")
dev.off()

#Define the correlation between single and merged replicates
han_correaltion_chiapet_mer_vs_2rep=c()
for (name in names(han_res_chiapet)){
  han_correaltion_chiapet_mer_vs_2rep[[name]]=cor(han_res_chiapet_rep2[[name]]$pval, han_res_chiapet[[name]]$pval, method = "spearman")
}

png(paste0('plots/Han_',experiment,'_correlation_pval_single_merged.png'), res = 300, width = 2200, height = 1100)
layout(matrix(c(1,3,7,2,4,8,2,5,9,2,6,10),ncol=4),heights=c(1,3,0.5,1,3,0.5,1,3,0.5,1,3,0.5), widths=c(2, 1.5, 1.5, 1.5))

par(mar=c(0,0,0,0))
plot.new()
text(0.5,0.5,"All trios",cex=1.5,font=2)
plot.new()
text(0.5,0.5,"Within pairs of trios",cex=1.5,font=2)

par(mar=c(4,4,1,0.5))
plot(-log10(han_res_chiapet_rep2[[1]]$pval), -log10(han_res_chiapet[[1]]$pval), col = "#0000FF14", pch = 20, xlab = "With Reps", ylab = "Without Reps")
plot(-log10(han_res_chiapet_rep2[[2]]$pval), -log10(han_res_chiapet[[2]]$pval), col = "#0000FF14", pch = 20, xlab = "With Reps", ylab = "Without Reps", main=names(han_res_chiapet_rep2)[[2]])
plot(-log10(han_res_chiapet_rep2[[3]]$pval), -log10(han_res_chiapet[[3]]$pval), col = "#0000FF14", pch = 20, xlab = "With Reps", ylab = "Without Reps", main=names(han_res_chiapet_rep2)[[3]])
plot(-log10(han_res_chiapet_rep2[[4]]$pval), -log10(han_res_chiapet[[4]]$pval), col = "#0000FF14", pch = 20, xlab = "With Reps", ylab = "Without Reps", main=names(han_res_chiapet_rep2)[[4]])

par(mar=c(0,0,0,0))
plot.new()
text(0.66, 0.66,paste0("cor = ",round(han_correaltion_chiapet_mer_vs_2rep[[1]],2)),cex=1,font=2)
plot.new()
text(0.66, 0.66,paste0("cor = ",round(han_correaltion_chiapet_mer_vs_2rep[[2]],2)),cex=1,font=2)
plot.new()
text(0.66, 0.66,paste0("cor = ",round(han_correaltion_chiapet_mer_vs_2rep[[3]],2)),cex=1,font=2)
plot.new()
text(0.66, 0.66,paste0("cor = ",round(han_correaltion_chiapet_mer_vs_2rep[[4]],2)),cex=1,font=2)

```

# Perform the analysis of the results ChIA-PET merged replicates
```{r}
experiment="ChIA-PET"
trios=c("HG00512", "HG00513", "HG00514")

# Create tables that will include all important information for the analysis
han_common_chiapet_manorm_merged=list(
  create_table_common_peaks_with_info(han_norm_chiapet, han_res_chiapet, han_conds_chiapet, trios[1:2]),              
  create_table_common_peaks_with_info(han_norm_chiapet, han_res_chiapet, han_conds_chiapet, trios[c(1,3)]),               
  create_table_common_peaks_with_info(han_norm_chiapet, han_res_chiapet, han_conds_chiapet, trios[2:3]))

names(han_common_chiapet_manorm_merged)=create_short_name_for_col(trios)


# Create additional tables with lower and higher values of mean values (select the squares)
mean_range=c(10,10)

han_common_chiapet_manorm_merged=add_greater_and_lower_mean_ranges_tables(han_common_chiapet_manorm_merged, mean_range, trios[1:2])
han_common_chiapet_manorm_merged=add_greater_and_lower_mean_ranges_tables(han_common_chiapet_manorm_merged, mean_range, trios[c(1,3)])
han_common_chiapet_manorm_merged=add_greater_and_lower_mean_ranges_tables(han_common_chiapet_manorm_merged, mean_range, trios[2:3])

# Create false pos tables
par="isPval"

han_pos_false_tables_chiapet_merged=list(
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[1]],trios[1:2], experiment, "all_mrgRep", par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[4]],trios[1:2], experiment, "mean>=10_mrgRep", par),      
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[5]],trios[1:2], experiment, "mean<10_mrgRep", par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[2]],trios[c(1,3)], experiment, "all_mrgBins", par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[6]],trios[c(1,3)], experiment, "mean>=10_mrgRep", par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[7]],trios[c(1,3)], experiment, "mean<10_mrgRep", par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[3]],trios[2:3], experiment, "all_mrgRep", par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[8]],trios[2:3], experiment, "mean>=10_mrgRep", par),
  create_fp_tables_and_save_graphs(han_common_chiapet_manorm_merged[[9]],trios[2:3], experiment, "mean<10_mrgRep", par))

names(han_pos_false_tables_chiapet_merged)=names(han_common_chiapet_manorm_merged)[c(1,4,5,2,6,7,3,8,9)]

# Create confusion tables for every pairs of replicates and freater and lower ranges                  
han_confusion_tables_chiapet_merged=vector(mode="list", length=NROW(han_pos_false_tables_chiapet_merged))
names(han_confusion_tables_chiapet_merged)=names(han_pos_false_tables_chiapet_merged)
for (i in 1:NROW(han_confusion_tables_chiapet_merged)){
  han_confusion_tables_chiapet_merged[i]=list(caret::confusionMatrix(factor(han_common_chiapet_manorm_merged[[names(han_confusion_tables_chiapet_merged)[i]]]$common_pval, levels=c(TRUE, FALSE)), 
                       factor(han_common_chiapet_manorm_merged[[names(han_confusion_tables_chiapet_merged)[i]]]$predicted_rev, levels=c(TRUE, FALSE)),
                       dnn=c("pval>0.05", "SPP_detected")))
}

# 4 CASES
han_confusion_data_chiapet_merged=list(
       # Both show common (TP)
  list(TP=han_pos_false_tables_chiapet_merged[[1]][[1]][han_pos_false_tables_chiapet_merged[[1]][[1]]$common_pval==TRUE,],
       # Spp pokazuje tak, a padj pokazuje róźną siłę (FP)
       FP=han_pos_false_tables_chiapet_merged[[1]][[1]][han_pos_false_tables_chiapet_merged[[1]][[1]]$common_pval==FALSE,], 
       # SPP pokazuje nie, a padj pokazuje, że siła jest taka sama (FN)
       FN=han_pos_false_tables_chiapet_merged[[1]][["false_peaks"]][han_pos_false_tables_chiapet_merged[[1]][["false_peaks"]]$common_pval==TRUE,],
       # SPP pokazuje nie i padj się zgadza  (TN)
       TN=han_pos_false_tables_chiapet_merged[[1]][["false_peaks"]][han_pos_false_tables_chiapet_merged[[1]][["false_peaks"]]$common_pval==FALSE,]),
  list(TP=han_pos_false_tables_chiapet_merged[[4]][[1]][han_pos_false_tables_chiapet_merged[[4]][[1]]$common_pval==TRUE,],
       
       # Spp pokazuje tak, a padj pokazuje róźną siłę (FP)
       FP=han_pos_false_tables_chiapet_merged[[4]][[1]][han_pos_false_tables_chiapet_merged[[4]][[1]]$common_pval==FALSE,],
       # SPP pokazuje nie, a padj pokazuje, że siła jest taka sama (FN)
       FN=han_pos_false_tables_chiapet_merged[[4]][["false_peaks"]][han_pos_false_tables_chiapet_merged[[4]][["false_peaks"]]$common_pval==TRUE,],
       # SPP pokazuje nie i padj się zgadza  (TN)
       TN=han_pos_false_tables_chiapet_merged[[4]][["false_peaks"]][han_pos_false_tables_chiapet_merged[[4]][["false_peaks"]]$common_pval==FALSE,]),
  
  list(TP=han_pos_false_tables_chiapet_merged[[7]][[1]][han_pos_false_tables_chiapet_merged[[7]][[1]]$common_pval==TRUE,],
       # Spp pokazuje tak, a padj pokazuje róźną siłę (FP)
       FP=han_pos_false_tables_chiapet_merged[[7]][[1]][han_pos_false_tables_chiapet_merged[[7]][[1]]$common_pval==FALSE,],
       # SPP pokazuje nie, a padj pokazuje, że siła jest taka sama (FN)
       FN=han_pos_false_tables_chiapet_merged[[7]][["false_peaks"]][han_pos_false_tables_chiapet_merged[[7]][["false_peaks"]]$common_pval==TRUE,],
       # SPP pokazuje nie i padj się zgadza  (TN)
       TN=han_pos_false_tables_chiapet_merged[[7]][["false_peaks"]][han_pos_false_tables_chiapet_merged[[7]][["false_peaks"]]$common_pval==FALSE,]))

names(han_confusion_data_chiapet_merged)=names(han_common_chiapet_manorm_merged)[1:3]

```


















Rest of the script
```{r}
# Check which  false peaks have big pval 
hichip_gm38T_gm40F=common_hichip.gm38_g40[common_hichip.gm38_g40$GM19238.occupancy==FALSE & 
                       common_hichip.gm38_g40$GM19240.occupancy==TRUE & 
                         common_hichip.gm38_g40$pval<0.001,]

common_chiapet.gm38_g40$isPval=ifelse(gm38_39_df$padj<0.001, TRUE, FALSE)
ggplot(common_chiapet.gm38_g39, aes(x=GM19238.mean, y=GM19239.mean))+geom_point(aes(col=isPval))+geom_smooth(method="lm", formula=y~x)

# Chech why false peaks have big pval
constant_df=data.frame(chrom=norm_hichip_2rep$chrom,
           start=norm_hichip_2rep$start,
           end=norm_hichip_2rep$end,
           res_hichip_rep2,
           conds_hichip_2rep$GM19238$norm.signal,
           conds_hichip_2rep$GM19239$norm.signal,
           conds_hichip_2rep$GM19240$norm.signal,
           conds_hichip_2rep$GM19238$occupancy,
           conds_hichip_2rep$GM19239$occupancy,
           conds_hichip_2rep$GM19240$occupancy)

constant_hichip_false=constant_df[which(constant_df$conds_hichip_2rep.GM19238.occupancy==FALSE & 
                       constant_df$conds_hichip_2rep.GM19239.occupancy==FALSE& 
                         constant_df$conds_hichip_2rep.GM19240.occupancy==TRUE & 
                         constant_df$padj>0.01),]
constant_hichip_false[sort(constant_hichip_false$pval, index.return=T,decreasing = TRUE)$ix,][1:10,]






# cos=norm_chiapet_eden_single_simple[which(norm_chiapet_eden_single_simple$GM19238.occupancy==1),]
norm_inp_hichip_2rep[sort(res_hichip_rep2$pval, index.return=T)$ix,]
norm_hichip_2rep[sort(res_hichip_rep2$pval, index.return=T)$ix,]

unique_38_39_hichip=which(norm_hichip_2rep$GM19238_rep1.occupancy==1 & 
                                             norm_hichip_2rep$GM19238_rep2.occupancy==1&
                                             norm_hichip_2rep$GM19239_rep1.occupancy==1 &
                                             norm_hichip_2rep$GM19239_rep2.occupancy==1)
norm_inp_hichip_2rep[unique_38_39_hichip,][sort(res_hichip_rep2[unique_38_39_hichip,]$pval, index.return=T)$ix,]
head(norm_inp_hichip_2rep[unique_38_39_hichip,][sort(res_hichip_rep2[unique_38_39_hichip,]$pval, index.return=T)$ix,])

norm_inp_hichip_2rep[sort(res_hichip_rep2_38_39[]$pval, index.return=T)$ix,]
norm_hichip_2rep[sort(res_hichip_rep2_38_39$pval, index.return=T)$ix,]




```
##### Identifying Hypervariable ChIP-seq Signals
```{r}
autosome <- !(norm_inp_hichip_2rep$chrom %in% c("chrX", "chrY"))
hyper_norm_hichip_2rep <- normalize(norm_inp_hichip_2rep, count = 4:9, occupancy = 10:15,
                  baseline = "pseudo-reference",
                  common.peak.regions = autosome)

# Construct a bioCond to group all the samples.
hyper_conds_hichip_2rep <- bioCond(hyper_norm_hichip_2rep[4:9], 
                                   hyper_norm_hichip_2rep[10:15], 
                                   occupy.num = 1,
                                   name = "all")

# Fit an MVC by using local regression.
# Set "nn = 1" to increase the smoothness of the resulting MVC.
hyper_conds_hichip_2rep <- fitMeanVarCurve(list(hyper_conds_hichip_2rep), method = "local",
                        occupy.only = TRUE, args.lp = list(nn = 1))[[1]]
summary(hyper_conds_hichip_2rep)

# Apply the parameter estimation framework of HyperChIP.(dramatic increase in the estimated number of prior degrees of freedom)
hyper_conds_hichip_2rep <- estParamHyperChIP(hyper_conds_hichip_2rep)
summary(hyper_conds_hichip_2rep)

# Perform statistical tests.
hyper_res_hichip_rep2 <- varTestBioCond(hyper_conds_hichip_2rep)
head(hyper_res_hichip_rep2)

# Visualize the overall test results.
hist(hyper_res_hichip_rep2$pval, breaks = 100, col = "red")
plot(hyper_res_hichip_rep2, padj = 0.01)

# one-sided p-values for identifying hypervariable ChIP-seq signals
df <- attr(hyper_res_hichip_rep2, "df")
one.sided.pval <- pf(hyper_res_hichip_rep2$fold.change, df[1], df[2], lower.tail = FALSE)

n <- rowSums(hyper_norm_hichip_2rep[10:15])
x <- list(All = -log10(one.sided.pval[n == 5]),
          Partially = -log10(one.sided.pval[n > 0 & n < 5]))
wilcox.test(x$All, x$Partially, alternative = "less")

boxplot(x, ylab = "-Log10(p-value)")
boxplot(x, ylab = "-Log10(p-value)", outline = FALSE)

# Measure the distance between each pair of samples.
d <- distBioCond(hyper_conds_hichip_2rep, method = "prior")

# Perform hierarchical clustering.
plot(hclust(d, method = "average"), hang = -1)

# Select hypervariable genomic intervals.
f <- hyper_res_hichip_rep2$fold.change > 1 & hyper_res_hichip_rep2$padj < 0.01
d2 <- distBioCond(hyper_conds_hichip_2rep, subset = f, method = "prior")
plot(hclust(d2, method = "average"), hang = -1)
```





















# MAnorms normalization
```{r}
### ChIA-PET ###
browseVignettes("MAnorm2")
library(MAnorm2)

experiment="chiapet"
manorms_input_chiapet.df=data.frame(read.table(
  paste0(abs_path, "/", experiment, "/narrow_peaks_profile_bins.xls"), header = T))
norm=normalize(manorms_input_chiapet.df, 4:6, 7:9)

manorms_input_chiapet_ref_bin=data.frame(read.table(paste0(abs_path, "/", experiment, "/fixed_size_profile_bins.xls"), header = T))
manorms_input_chiapet_ref_bin.gr=GRanges(manorms_input_chiapet_ref_bin)
norm_ref_bins_chiapet=normalize(manorms_input_chiapet_ref_bin, 4:6, 7:9)

# From cluster

norm_inp_chiapet_eden_paired=data.frame(read.table(paste0(abs_path, "/", experiment, "/ref_bins_paired_profile_bins.xls"), header = T))
norm_chiapet_eden_paired=MAnorm2::normalize(norm_inp_chiapet_eden_paired, 4:6, 7:9)
unique40_chiapet_paired=norm_inp_chiapet_eden_paired[which(norm_inp_chiapet_eden_paired$GM19240.occupancy==1),]
unique40_chiapet_paired[sort(unique40_chiapet_paired$GM19240.read_cnt, index.return=T)$ix,]


norm_inp_chiapet_eden_single=data.frame(read.table(paste0(abs_path, "/", experiment, "/ref_bins_single_profile_bins.xls"), header = T))
norm_chiapet_eden_single=MAnorm2::normalize(norm_inp_chiapet_eden_single, 4:6, 7:9)
#sort by the lowest value of GM19238.read_cnt
norm_chiapet_eden_single[sort(norm_chiapet_eden_single$GM19238.read_cnt, index.return=T)$ix,]
# Select only true peaks for cell_line
unique40_chiapet=norm_chiapet_eden_single[which(norm_chiapet_eden_single$GM19240.occupancy==1),]
unique40_chiapet[sort(unique40_chiapet$GM19240.read_cnt, index.return=T)$ix,]

unique39_chiapet=norm_chiapet_eden_single[which(norm_chiapet_eden_single$GM19239.occupancy==1),]
unique39_chiapet[sort(unique39_chiapet$GM19239.read_cnt, index.return=T)$ix,]

unique38_chiapet=norm_chiapet_eden_single[which(norm_chiapet_eden_single$GM19238.occupancy==1),]
unique38_chiapet[sort(unique38_chiapet$GM19238.read_cnt, index.return=T)$ix,]



constant_chiapet=norm_chiapet_eden_single[ which(norm_chiapet_eden_single$GM19238.occupancy==1 & 
                                                   norm_chiapet_eden_single$GM19239.occupancy==1 & 
                                                   norm_chiapet_eden_single$GM19240.occupancy==1),]
constant_chiapet[sort(constant_chiapet$GM19238.read_cnt, index.return=T)$ix,]
constant_chiapet[sort(constant_chiapet$GM19239.read_cnt, index.return=T)$ix,]
constant_chiapet[sort(constant_chiapet$GM19240.read_cnt, index.return=T)$ix,]

### with dedup chiapet

norm_inp_chiapet_eden_single_simple=data.frame(read.table(paste0(abs_path, "/", experiment, "/chiapet_single_simple_profile_bins.xls"), header = T))
norm_chiapet_eden_single_simple=MAnorm2::normalize(norm_inp_chiapet_eden_single_simple, 4:6, 7:9)
#sort by the lowest value of GM19238.read_cnt
norm_chiapet_eden_single_simple[sort(norm_chiapet_eden_single_simple$GM19238.read_cnt, index.return=T)$ix,]
# Select only true peaks for cell_line
unique38_chiapet_simple=norm_chiapet_eden_single_simple[which(norm_chiapet_eden_single_simple$GM19238.occupancy==1),]
unique38_chiapet_simple[sort(unique38_chiapet_simple$GM19238.read_cnt, index.return=T)$ix,]

unique39_chiapet_simple=norm_chiapet_eden_single_simple[which(norm_chiapet_eden_single_simple$GM19239.occupancy==1),]
unique39_chiapet_simple[sort(unique39_chiapet_simple$GM19239.read_cnt, index.return=T)$ix,]

unique40_chiapet_simple=norm_chiapet_eden_single_simple[which(norm_chiapet_eden_single_simple$GM19240.occupancy==1),]
unique40_chiapet_simple[sort(unique40_chiapet_simple$GM19240.read_cnt, index.return=T)$ix,]





constant_chiapet_simple=norm_chiapet_eden_single_simple[ which(norm_chiapet_eden_single_simple$GM19238.occupancy==1 & 
                                                   norm_chiapet_eden_single_simple$GM19239.occupancy==1 & 
                                                   norm_chiapet_eden_single_simple$GM19240.occupancy==1),]
constant_chiapet_simple[sort(constant_chiapet_simple$GM19238.read_cnt, index.return=T)$ix,]
constant_chiapet_simple[sort(constant_chiapet_simple$GM19239.read_cnt, index.return=T)$ix,]
constant_chiapet_simple[sort(constant_chiapet_simple$GM19240.read_cnt, index.return=T)$ix,]


### Workflow proposed by CRAN ###
# One-step normalization
norm=MAnorm2::normalize(norm_inp_chiapet_eden_single_simple, c(4,5,6), c(7,8,9))
raw = log(norm_inp_chiapet_eden_single_simple[4:6] + 0.5, base = 2)

# Plot correlation between the samples
plot(attr(norm, "MA.cor"), symbreaks = TRUE, margins = c(8, 8),
     cexRow = 1, cexCol = 1)

#MA plots
png(paste0('ChIAPET_MAnorm_normalization_.png'), res = 300, width = 4200, height = 4200)
# Generating new plots and data (log2)

par(mar=c(3,3,3,3))
layout(matrix(c(1,2,3,4,5,6,1,7,3,8,5,9),ncol=2),heights=c(1,3,1,3,1,3))
plot.new()
text(0.5,0.5,"GM19238 vs GM19239",cex=3,font=2)
generate_manorm_plot(trios[1:2], norm, raw)
plot.new()
text(0.5,0.5,"GM19238 vs GM19240",cex=3,font=2)
generate_manorm_plot(trios[c(1,3)], norm, raw)
plot.new()
text(0.5,0.5,"GM19239 vs GM19240",cex=3,font=2)
generate_manorm_plot(trios[2:3], norm , raw)
#After normalization
generate_manorm_plot(trios[1:2], norm)
generate_manorm_plot(trios[c(1,3)], norm)
generate_manorm_plot(trios[2:3], norm)
dev.off()

# Converting to bioCond
conds=list(GM19238=bioCond(norm[[4]], norm[[7]], name="GM19238"),
           GM19239=bioCond(norm[[5]], norm[[8]], name="GM19239"),
           GM19240=bioCond(norm[[6]], norm[[9]], name="GM19240"))

### Create a "blind" biocond, to compare two groups and not two samples

# Between 38 and 39
conds$blind_38_39 <- bioCond(norm[c(4, 5)], norm[c(7, 8)], occupy.num = 2,
                       name = "blind_38_39")
conds_38_39 <- fitMeanVarCurve(conds[c(1, 2, 4)], method = "parametric",
                         occupy.only = TRUE, init.coef = c(0.1, 10))
# Visualize mean-variance trend along with the fitted MVC.
plotMeanVarCurve(conds_38_39[3], subset = "occupied", ylim = c(-7, 1))

#Between 38 and 40
conds$blind_38_40 <- bioCond(norm[c(4, 6)], norm[c(7, 9)], occupy.num = 2,
                       name = "blind_38_40")
conds_38_40 <- fitMeanVarCurve(conds[c(1, 3, 5)], method = "parametric",
                         occupy.only = TRUE, init.coef = c(0.1, 10))
# Visualize mean-variance trend along with the fitted MVC.
plotMeanVarCurve(conds_38_40[3], subset = "occupied", ylim = c(-7, 1))

#Between 39 and 40
conds$blind_39_40 <- bioCond(norm[c(5, 6)], norm[c(8, 9)], occupy.num = 2,
                       name = "blind_39_40")
conds_39_40 <- fitMeanVarCurve(conds[c(2, 3, 6)], method = "parametric",
                         occupy.only = TRUE, init.coef = c(0.1, 10))
# Visualize mean-variance trend along with the fitted MVC.
plotMeanVarCurve(conds_39_40[3], subset = "occupied", ylim = c(-7, 1))

# Between all 3 cell-lines
conds$blind_common <- bioCond(norm[c(4, 5, 6)], norm[c(7, 8, 9)], occupy.num = 3,
                       name = "blind_common")
conds_common <- fitMeanVarCurve(conds[c(1, 2, 3, 7)], method = "parametric",
                         occupy.only = TRUE, init.coef = c(0.1, 10))
# Visualize mean-variance trend along with the fitted MVC.
plotMeanVarCurve(conds_common[4], subset = "occupied", ylim = c(-7, 1))



### # Perform differential tests.
res_38_39 <- diffTest(conds_38_39[[1]], conds_38_39[[2]])
res_38_40 <- diffTest(conds_38_40[[1]], conds_38_40[[2]])
res_39_40 <- diffTest(conds_39_40[[1]], conds_39_40[[2]])

MAplot(res_38_39, pval = 0.01, ylim=c(-3, 3), main="GM19238 vs GM19239")
abline(h = 0, lwd = 2, lty = 5, col = "green3")

MAplot(res_38_40, pval = 0.01)
abline(h = 0, lwd = 2, lty = 5, col = "green3")

MAplot(res_39_40, pval = 0.01)
abline(h = 0, lwd = 2, lty = 5, col = "green3")

cor(res_39_40$pval, res_39_40$pval, method = "spearman")


# 3 groups simulaniously

norm <- normalize(norm_inp_chiapet_eden_single_simple, count = 4, occupancy = 7)
norm <- normalize(norm, count = 5, occupancy = 8)
norm <- normalize(norm, count = 6, occupancy = 9)

conds <- list(GM19238 = bioCond(norm[4], norm[7], name = "GM19238"),
              GM19239 = bioCond(norm[5], norm[8], name = "GM19239"),
              GM19240 = bioCond(norm[6], norm[9], name = "GM19240"))

conds_plot <- fitMeanVarCurve(conds[c(1,2, 3,  7)], method = "parametric", occupy.only = TRUE, init.coef = c(0.1, 10))
res <- aovBioCond(conds_plot)
plot(res,  pval = 0.01)
plot(res,  padj = 1e-6, main="GM19238 vs GM19239 vs GM19240")



```



