---
title: "Loops_analysis_merged_replicates"
---

---
title: "Loops_analysis_single_replicates"
---

[ChIA-PET merged replicates] Upload the loops 

```{r}
experiment="chiapet"
trios=c("GM19238", "GM19239", "GM19240")

# Read loops files - all
loops_chiapet_all=vector(mode="list", length=NROW(trios))
names(loops_chiapet_all)=trios
for (cell_line in trios){
  loops_chiapet_all[[cell_line]]=read.table(
    list.files(paste0("data/", experiment, "/", cell_line), pattern='\\.e500.clusters.cis.BE3$', recursive=FALSE, full.names = TRUE))
  colnames(loops_chiapet_all[[cell_line]])=c("anch_1","start_1","end_1","anch_2","start_2","end_2","pets_count")
}

# Read loops files - all
loops_chiapet_2_anchors=vector(mode="list", length=NROW(trios))
names(loops_chiapet_2_anchors)=trios
for (cell_line in trios){
  loops_chiapet_2_anchors[[cell_line]]=read.table(
    list.files(paste0("data/", experiment, "/", cell_line), pattern='.e500.clusters.cis.BE3.peak_annot.E2$', recursive=FALSE, full.names = TRUE))
  colnames(loops_chiapet_2_anchors[[cell_line]])=c("anch_1","start_1","end_1","anch_2","start_2","end_2","pets_count")
}
```


[HiChIP merged replicates] Upload the loops 

```{r}
experiment="hichip"
trios=c("GM19238", "GM19239", "GM19240")

# Read loops files - all
loops_hichip_all=vector(mode="list", length=NROW(trios))
names(loops_hichip_all)=trios
for (cell_line in trios){
  loops_hichip_all[[cell_line]]=read.table(
    list.files(paste0("data/", experiment, "/", cell_line), pattern='\\.e500.clusters.cis.BE3$', recursive=FALSE, full.names = TRUE))
  colnames(loops_hichip_all[[cell_line]])=c("anch_1","start_1","end_1","anch_2","start_2","end_2","pets_count")
}

# Read loops files - all
loops_hichip_2_anchors=vector(mode="list", length=NROW(trios))
names(loops_hichip_2_anchors)=trios
for (cell_line in trios){
  loops_hichip_2_anchors[[cell_line]]=read.table(
    list.files(paste0("data/", experiment, "/", cell_line), pattern='.e500.clusters.cis.BE3.peak_annot.E2$', recursive=FALSE, full.names = TRUE))
  colnames(loops_hichip_2_anchors[[cell_line]])=c("anch_1","start_1","end_1","anch_2","start_2","end_2","pets_count")
}
```

# [ChIA-PET single replicates] Compare the all loops quantity

```{r}

experiment="chiapet"

# Generate the comulative distribution plot

png(paste0('plots/loops/Comulative_distribution_plot_', experiment, '_all_loops_merged_replicates.png'), res = 300, width = 1500, height = 1500)

plot.new()
i=n=1
for (cell_line in trios){
  ecdf_plot=plot(ecdf(loops_chiapet_all[[cell_line]]$pets_count),
     cex=0.5,
     # xlim=c(3,max(loops_chiapet_all[[cell_line]]$pets_count)),
     xlim=c(3,50),
     col=color(cell_line),
     ylim=c(0.2,1), add=ifelse(n==1, FALSE, TRUE),
     xlab="PETs count",
     ylab="Cumulative percent",
     # pch=19)
     pch=19,
     main="")
  n=n+1
  if(n==3 | n==5){i=i+1}}
legend("bottomright", 
       title="Cell Line",
       legend=trios,
       pch=c(19,19,19),
       col=c(color(trios[1]), color(trios[2]), color(trios[3])))
dev.off()

# png(paste0('plots/loops/Comulative_distribution_plot_two_experiments_all_loops_merged_replicates.png'), res = 300, width = 1500, height = 1500)
# 
# experiments=c("chiapet", "hichip")
# plot.new()
# i=n=1
# for (experiment in experiments){
#   loops_tmp=ifelse (experiment=="chiapet", "loops_chiapet_all", "loops_hichip_all")
# 
#   for (cell_line in trios){
#     ecdf_plot=plot(ecdf(get(loops_tmp)[[cell_line]]$pets_count),
#        cex=0.5,
#        # xlim=c(3,max(loops_tmp[[cell_line]]$pets_count)),
#        xlim=c(3,50),
#        col=color(cell_line),
#        ylim=c(0.2,1), add=ifelse(n==1, FALSE, TRUE),
#        xlab="PETs count",
#        ylab="Cumulative percent",
#        pch=ifelse(experiment=="chiapet",0, 19),
#        main="")
#     n=n+1
#   }
# }
# legend("bottomright", 
#        title="Cell Line",
#        legend=c("GM19238_ChIA-PET", "GM19239_ChIA-PET", "GM19240_ChIA-PET", 
#                 "GM19238_HiChIP", "GM19239_HiChIP", "GM19240_HiChIP"),
#        pch=c(0,0,0,19,19,19),
#        col=c(color(trios[1]), color(trios[2]), color(trios[3]), color(trios[1]), color(trios[2]), color(trios[3])))
# dev.off()

# See the cumulative numbers
# ecdf(loops_chiapet_all[[cell_line]]$pets_count)(sort(loops_chiapet_all[[cell_line]]$pets_count))

# Calculate the average PETs number of 99% of replicates and mean in the sample
chiapet_cum_percent_loops=vector(mode="list", length=NROW(loops_chiapet_all))
names(chiapet_cum_percent_loops)=trios
for (cell_line in trios){
  chiapet_cum_percent_loops[[cell_line]]=
    c(quantile(loops_chiapet_all[[cell_line]]$pets_count, probs=seq(0,1,0.99)),
  mean(loops_chiapet_all[[cell_line]]$pets_count))
  names(chiapet_cum_percent_loops[[cell_line]])[3]="mean"
}

```

# [HiChIP single replicates] Compare the all loops quantity

```{r}

experiment="hichip"

# Generate the comulative distribution plot

png(paste0('plots/loops/Comulative_distribution_plot_', experiment, '_all_loops_merged_replicates.png'), res = 300, width = 1500, height = 1500)

plot.new()
i=n=1
for (cell_line in trios){
  ecdf_plot=plot(ecdf(loops_hichip_all[[cell_line]]$pets_count),
     cex=0.5,
     # xlim=c(3,max(loops_hichip_all[[cell_line]]$pets_count)),
     xlim=c(3,50),
     col=color(cell_line),
     ylim=c(0.2,1), add=ifelse(n==1, FALSE, TRUE),
     xlab="PETs count",
     ylab="Cumulative percent",
     # pch=19)
     pch=19,
     main="")
  n=n+1
  if(n==3 | n==5){i=i+1}}
legend("bottomright", 
       title="Cell Line",
       legend=trios,
       pch=c(19,19,19),
       col=c(color(trios[1]), color(trios[2]), color(trios[3])))
dev.off()

# See the cumulative numbers
# ecdf(loops_hichip_all[[cell_line]]$pets_count)(sort(loops_hichip_all[[cell_line]]$pets_count))

# Calculate the average PETs number of 99% of replicates and mean in the sample
hichip_cum_percent_loops=vector(mode="list", length=NROW(loops_hichip_all))
names(hichip_cum_percent_loops)=trios
for (cell_line in trios){
  hichip_cum_percent_loops[[cell_line]]=
    c(quantile(loops_hichip_all[[cell_line]]$pets_count, probs=seq(0,1,0.99)),
  mean(loops_hichip_all[[cell_line]]$pets_count))
  names(hichip_cum_percent_loops[[cell_line]])[3]="mean"
}

```

# [ChIA-PET merged replicates] Compare the loops with 2 anchors quantity

```{r}
experiment="chiapet"

# Generate the comulative distribution plot

png(paste0('plots/loops/Comulative_distribution_plot_', experiment, '_2_anchors_merged_replicates.png'), res = 300, width = 1500, height = 1500)

plot.new()
i=n=1
for (cell_line in trios){
  ecdf_plot=plot(ecdf(loops_chiapet_2_anchors[[cell_line]]$pets_count),
     cex=0.5,
     # xlim=c(3,max(loops_chiapet_2_anchors[[cell_line]]$pets_count)),
     xlim=c(3,50),
     col=color(cell_line),
     ylim=c(0.2,1), add=ifelse(n==1, FALSE, TRUE),
     xlab="PETs count",
     ylab="Cumulative percent",
     # pch=19)
     pch=19,
     main="")
  n=n+1
  if(n==3 | n==5){i=i+1}}
legend("bottomright", 
       title="Cell Line",
       legend=trios,
       pch=c(19,19,19),
       col=c(color(trios[1]), color(trios[2]), color(trios[3])))
dev.off()

# Calculate the average PETs number of 99% of replicates and mean in the sample
chiapet_cum_percent_2anch_loops=vector(mode="list", length=NROW(loops_chiapet_2_anchors))
names(chiapet_cum_percent_2anch_loops)=trios
for (cell_line in trios){
  chiapet_cum_percent_2anch_loops[[cell_line]]=
    c(quantile(loops_chiapet_2_anchors[[cell_line]]$pets_count, probs=seq(0,1,0.99)),
  mean(loops_chiapet_2_anchors[[cell_line]]$pets_count))
  names(chiapet_cum_percent_2anch_loops[[cell_line]])[3]="mean"
}
```

# [HiChIP merged replicates] Compare the loops with 2 anchors quantity

```{r}
experiment="hichip"

# Generate the comulative distribution plot

png(paste0('plots/loops/Comulative_distribution_plot_', experiment, '_2_anchors_merged_replicates.png'), res = 300, width = 1500, height = 1500)

plot.new()
i=n=1
for (cell_line in trios){
  ecdf_plot=plot(ecdf(loops_hichip_2_anchors[[cell_line]]$pets_count),
     cex=0.5,
     # xlim=c(3,max(loops_hichip_all[[cell_line]]$pets_count)),
     xlim=c(3,50),
     col=color(cell_line),
     ylim=c(0.2,1), add=ifelse(n==1, FALSE, TRUE),
     xlab="PETs count",
     ylab="Cumulative percent",
     # pch=19)
     pch=19,
     main="")
  n=n+1
  if(n==3 | n==5){i=i+1}}
legend("bottomright", 
       title="Cell Line",
       legend=trios,
       pch=c(19,19,19),
       col=c(color(trios[1]), color(trios[2]), color(trios[3])))
dev.off()

# Calculate the average PETs number of 99% of replicates and mean in the sample
hichip_cum_percent_2anch_loops=vector(mode="list", length=NROW(loops_hichip_2_anchors))
names(hichip_cum_percent_2anch_loops)=trios
for (cell_line in trios){
  hichip_cum_percent_2anch_loops[[cell_line]]=
    c(quantile(loops_hichip_2_anchors[[cell_line]]$pets_count, probs=seq(0,1,0.99)),
  mean(loops_hichip_2_anchors[[cell_line]]$pets_count))
  names(hichip_cum_percent_2anch_loops[[cell_line]])[3]="mean"
}
```

